### ISSUE TITLE
ビルドエラーが発生している

### ISSUE THREAD

**Issue by halsk** [codeforjapan/mynumbercard_statistics#173]
8月18日から、以下のエラーが発生するようになった。(数週間、特にソースコードへの変更は行っていない。)

```
Step 6/9 : RUN apt-get update -y && apt-get install -y python-opencv libopencv-dev ghostscript    && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Running in c42ba3032cd6
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [113 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [36.8 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [25.8 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8178 kB]
Fetched 8397 kB in 2s (5142 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package python-opencv
The command '/bin/sh -c apt-get update -y && apt-get install -y python-opencv libopencv-dev ghostscript    && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

Error: Process completed with exit code 100.
```

**Comment by halsk** [comment]
@aruneko 氏によるPR #174 で上記エラーは修正されたが、今度は以下のエラーが発生

```
Creating mynumbercard_statistics_app_run ... done
Traceback (most recent call last):
  File "mynumbercard_data/download.py", line 15, in <module>
    import camelot
  File "/usr/local/lib/python3.8/site-packages/camelot/__init__.py", line 6, in <module>
    from .io import read_pdf
  File "/usr/local/lib/python3.8/site-packages/camelot/io.py", line 5, in <module>
    from .handlers import PDFHandler
  File "/usr/local/lib/python3.8/site-packages/camelot/handlers.py", line 9, in <module>
    from .parsers import Stream, Lattice
  File "/usr/local/lib/python3.8/site-packages/camelot/parsers/__init__.py", line 4, in <module>
    from .lattice import Lattice
  File "/usr/local/lib/python3.8/site-packages/camelot/parsers/lattice.py", line 26, in <module>
    from ..image_processing import (
  File "/usr/local/lib/python3.8/site-packages/camelot/image_processing.py", line 3, in <module>
    import cv2
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
1
Makefile:5: recipe for target 'download' failed
make: *** [download] Error 1
Error: Process completed with exit code 2.
```

**Comment by halsk** [comment]
あ、これは別の問題かも。master と development の同期が取れていなかった

**Comment by halsk** [comment]
いや、同期しても発生しました。調べてみます。

**Comment by halsk** [comment]
#177 で修正されました！
@aruneko さん、ありがとうございました！
